# Skilningur {#skilning}

Hvað er skilningur? Hvað er skilningur í stærðfræði?

## Venslaskilningur og tækniskilningur {#vensla-taekni}

Við getum rifjað upp tvígreiningu Richard Skemps í venslaskilning og tækniskilning [@skemp1976]. Í örstuttu máli drögum við þessi hugtök saman:

* Venslaskilningur er að vita hvernig hægt er að nota stærðfræðihugtök og -aðferðir og vita hvers vegna þær eru viðeigandi og hvers vegna þær skila réttum niðurstöðum.
* Tækniskilningur er að vita hvernig á að reikna tiltekin dæmi án þess að vita hvers vegna þau eru reiknuð á þann hátt, hvort það sé vit í reikningunum, eða hvernig aðferðin tengist öðrum aðferðum eða hugtökum.

Í bók Picciotto og Pemantle er *skilningur* nokkurn veginn það sama og Skemp kallar venslaskilning.

## Skilningur í daglegu máli og í stærðfræði {#skiln-dag-stae}

Til frekari dýptar getum við velt fyrir okkur hvað orðið skilningur eiginlega merkir. Í skáldsögu Fríðu Ísberg, *Merking* [@isberg2021] (annað mikilvægt hugtak!) segir:

> Íslenska orðið „skilningur“ hefur ákveðna einangrunarmerkingu; við reynum að skilja eitt frá öðru - hið ljóta frá hinu fallega, manninn frá dýrinu - til að einangra það og eyða svo því sem við viljum ekki. En latneska orðið „comprehendere“ - sem enskan notar - er andstæða þess: það þýðir að taka saman. „Com-“ er svipað forskeyti og „sam-“ á íslensku og „prehendere“ þýðir að grípa, ná tökum á einhverju. (bls. 194)

Fleiri rannsakendur hafa lagt áherslu á að skilningur felist í að aðskilja, greina sundur, og líka að taka saman, ná utan um, grípa um. Mjög fróðleg umfjöllun um skilning í íslensku og í sögulegu ljósi kennslubóka í stærðfræði er í grein Kristínar Bjarnadóttur, *Er áhersla á skilning nýmæli?* [@bjarnadottir2022]

Til að skýra betur hvað það merkir að *skilja hugtak* segja Picciotto og Pemantle að það að skilja hugtak ætti yfirleitt að þýða að nemandi geti:

-   Útskýrt það með eigin orðum, útskýra *hvers vegna* eitthvað er eins og það er. Kennarar ættu því að biðja nemendur reglulega að útskýra, bæði munnlega og skriflega (og það getur stundum átt við að teikna eða beita  líkamstjáningu til stuðnings).
-   Að snúa ferlum við. Þú skilur ekki dreifireglu nema þú getir þáttað líka, þú skilur ekki jöfnur nema þú getir búið til (margar) jöfnur sem hafa lausnina $4$, og getir búið til jöfnu út frá grafi. Það að geta snúið við ferlum (e. reversibility) er prófsteinn á skilning, leið til að dýpka skilning, og í sumum tilvikum önnur leið að skilningi.
-   Svegjanleg notkun margra leiða. Að skilja jöfnur: með prófun, með gröfum, með töflum, með tækni, auk bókstafareiknings.
-   Að geta *tengt milli ólíkra framsetninga*, til dæmis tákna (algebrustæða), töflu (gildistöflu) og grafs (teikning í hnitakerfi).
-   Yfirfærsla á ný samhengi. Til dæmis að tengja hlutföll við einslaga myndir, og fjarlægð milli punkta við reglu Pýþagórasar.
-   Að vita hvenær það á ekki við. Dæmi: ekki eru öll sambönd línuleg. Þess vegna er mikilvægt að rannsaka gagndæmi, hvenær eitthvað á ekki við.

Við bætum við eftirfarandi (sem geta þó líklega átt við sem sértilfelli undir einhverjum af punktunum hér að ofan):

- Að geta gefið eigin dæmi sem falla undir hugtakið og dæmi sem falla *ekki* undir hugtakið (og útskýrt hvers vegna dæmin eru þannig). Sjá meira um þetta í undirkafla \@ref(breytileiki), *Breytileiki*.
- Að útskýra hvernig það tengist öðrum hugtökum.

Einn stærsti vandinn við stærðfræðikennslu til skilnings er að það er ómögulegt að veita einhverjum skilning með því einu að útskýra.

### Verkefni um dreifireglu {#verkefni-dreifiregla}

Hugsum okkur spurninguna

> Af hverju er $2(x+3) = 2x + 6$?

Hvaða ályktanir um skilning nemanda getum dregið út frá eftirfarandi „svörum“, og hvernig gætum við brugðist við svörunum til að kanna skilninginn betur:

1.  „Það er út af dreifireglunni?“
2.  „Til dæmis ef $x=1$ þá þetta bara $2(1+3)=2 \cdot 4$ og það er alveg eins hægt að skipta $4$ niður og margfalda hvern hlut fyrir sig, $2 \cdot 1 = 2$ og $2 \cdot 3 = 6$ og leggja saman, $2+6=8$.
3.  „Ef ég skoða rétthyrning með eina hlið $2$ og hina $x+3$ og reikna flatarmálið, þá skiptir ekki máli hvort ég reikna hvern bút fyrir sig og legg saman eða allan í einu“ (með fylgir eftirfarandi teikning):

```{r reitir, echo=FALSE, fig.cap="Rétthyrningur með reitum af breidd $x$ og $3$ og hæð $2$.", fig.width=6, fig.height=2}
teikna_reiti(n = 4, m = 3, h = 2)
```

## Breytileiki {#breytileiki}

Stærðfræðihugtök og setningar (niðurstöður) fela oft í sér að benda á  eitthvað sem breytist á meðan annað er óbreytt. John Mason notar hugtökin *breytileikavíddir* (dimensions of possible variation) og *breytileikamörk* (range of permissible change) til að lýsa breytileika [@mason2005]. Hægt er að breyta tilteknum hlutum í einhverju verkefni þannig að það haldi áfram að vera dæmi um það sama, en það fer alltaf eftir því hvað við hugsum um sem „það sama“ í hverju tilfelli (og getur verið mismunandi eftir samhengi). Það getur verið gagnlegt að greina hverju er hægt að breyta (hverjar eru  breytileikavíddirnar) og hvernig (hver eru breytileikamörkin) þannig að nákvæmlega sama aðferð virki áfram til að leysa verkefni. Við getum líka beitt þessum hugtökum á stærðfræðileg fyrirbæri út af fyrir sig. Til dæmis eru $5+7=12$ og $4+8=12$ og við getum velt fyrir okkur breytileikavíddum og breytileikamörkum. Hvað breytist og hvað er óbreytt í þessum jöfnum? Hverju má breyta til að fá fram fleiri „eins“ jöfnur? Hvernig? 

## Breytileikaverkefni 1 {#verkefni_breytileiki_1}

Segið um hverja röð hvað breytist og hvað breytist ekki. Undir hvaða hugtök falla öll dæmin (í sama lið)? Hér má nefna nokkur misjafnlega þröng hugtök. Bætið við fleiri dæmum um það sama. Það sem breytist endurspeglar breytileikavídd (hverju má breyta). Bætið svo við dæmum sem falla ekki undir þrengsta hugtakið, með öðrum orðum: búið til dæmi sem fer út fyrir eitthvað sem breytist ekki í þeim dæmum sem gefin eru. Ramminn endurspeglar breytileikamörk (hvernig má breyta).  

1. $\frac{1}{2}, \frac{2}{4}, \frac{3}{6}, \frac{4}{8}$
1. $x+y=1$, $2x+2y=2$, $4x+4y=4$
1. $x+y=1$, $2x+2y=1$, $3x+3y=1$
1. $x+y=1$, $4x-2y=1$, $8x-6y=1$
1. $f(x)=x^2$, $f(x)=x^2+1$, $f(x)=x^2+2$





