# Um námsmat i stærðfræði {#namsmat_kafli}

Hér eru nokkur atriði til umhugsunar úr bók Picciotto og Pemantle, með smávægilegum viðbótarútleggingum: 

* Það er ekki hægt að kenna nema að hafa hugmynd um hver skilningur nemenda á efninu er. Hér er ekki átt við að hafa mælt nemendur á skala frá til dæmis litlum skilningi að góðum skilningi heldur að kennarinn viti í raun og veru eitthvað um það **hvernig** (á hvaða hátt) nemendur skilja hugtök, röksemdir og aðferðir. Þess vegna er námsmat mikilvægur þáttur í kennslu.
* Höfum í huga að yfirferð (að leiðrétta og gefa einkunn fyrir) verkefna er ekki endilega góð nýting á tíma. Þú leiðréttir eitt verkefni í einu og það getur því tekið mikinn tíma að fara yfir námsmatsverkefni margra einstakra nemenda. Ef til vill væri hægt að nýta þann tíma betur? Til dæmis gætu nemendur tekið þátt í þessu, leiðrétt sín eigin verkefni eða annarra, með aðstoð eða svarlyklum.
* Námsmat getur stutt kennara í því að stilla kennsluna á hæfilegt stig, endurskoða kennsluna. 
* Námsmat getur gefið bæði kennara og nemanda upplýsingar um það hver hæfni nemandans er.
* Námsmat getur verið námstækifæri.

Allur sá tilgangur sem nefndur var hér að ofan næst best ef lítið er í húfi ("low-stakes"). Útkoma námsmatsins á ekki að vera refsing (og ekki heldur umbun). Fyrir þann tilgang að bæta nám er ekki nauðsynlegt að gefa einkunnir fyrir námsmatsverkefni, hvort heldur sem er á formi bókstafa, lita eða talna. En svo er það háð reglum skólans, sveitarfélaga og ríkis hvort og hvenær kennari þarf nauðsynlega að gefa einkunnir. 

## Próf og kannanir

Fyrir kennara sem vinna í umhverfi þar sem þarf að gefa einkunnir er hagkvæmast að halda lítil próf eða kannanir. En það eru nokkur atriði sem hægt er að hafa í huga til þess að gera þau betri ef tilgangurinn er að styðja við nám. Þessi atriði eru frá Picciotto og Pemantle:

* Leyfið nemendum að fá eins mikinn tíma og þeir þurfa. Tímapressa hjálpar engum að sýna skilning sinn.
* Ekki draga of mikið niður fyrir litlar reiknivillur. Setjið skilning í forgang. Hafið þó í huga að stundum eru reiknivillur vegna skorts á skilningi og það eru ekki þannig villur sem átt er við hér. 
* Látið reyna á skilning á efni sem er ekki alveg nýtt fyrir nemendum. 
* Hafið kannanir þar sem reynir á uppsafnað efni, allt frá byrjun annar.
* Hafið með „bónus“ spurningar sem eru áskoranir fyrir sterkustu nemendurna, spurningar sem dýpka eða víkka út skilning á efninu. Þessar spurningar geta svo komið að notum fyrir alla nemendur í eftirvinnslu könnunar. En það á að vera hægt að fá hæstu einkunn án þess að leysa þessi verkefni.

Annað sem þessir höfundar stinga upp á er að meta þátttöku nemenda „í beinni“ þar sem kennari fylgist með því hvort nemendur séu að vinna vel, skráir það hjá sér og varpar upp á sýnilegan flöt. Dæmi um það sem kennari getur skráð eru hlutir eins og „Jón fór strax að vinna við verkefnið“, „Silja er að hjálpa Gunnari með erfitt verkefni“, „Nadira er að færa sig nær hópnum til að heyra betur útskýringarnar“. 

## Eftirvinnsla og endurtekningar

Hér er eitt mikilvægasta ráðið um próf og kannanir í bók Picciotto og Pemantle: 

* Látið leiðréttingar og úrvinnslu prófa „gilda“. Takið frá tíma í þetta. Hér skiptir máli að nemendur sjálfir bæti sínar lausnir og þeir megi hjálpast að og geti fengið stuðning kennara líka. Eftir slíka úrvinnslu ættu svörin líka að uppfylla meiri kröfur en á prófinu sjálfu. 

Við þetta má bæta að það er hægt að skipuleggja þessa eftirávinnu með mismunandi hætti. Ein leið er að segja að könnunin sjálf gildi (til dæmis) 70% en að eftirávinnslan gildi 30%, eða prófið eftir þá vinnslu gildi 30%. Það er líka hægt að láta nemendur fá sínar lausnir í hendur (óleiðréttar) og þeim svo skipt í hópa þar sem hver hópur fær eitt tómt próf og býr saman til sína bestu lausn á prófinu sem þá gildir (til dæmis) 30% á móti upphaflega prófinu. Hér skal ítrekað að vægið á prófinu í heild ætti helst að vera lítið (low stakes) og að prósenturnar hér eru bara ein uppástunga. Það sem skiptir máli er grundvallaratriðið að eftirvinnsla verkefnisins skipti máli og fari fram. 

Í kafla Picciotto og Pemantle er töluverð umræða um slæmar röksemdir gegn því að nemendur fái að endurtaka próftöku. Lykilpunktarnir þar ganga í raun út á að útskýra að nemendur auki ekki skilning sinn með þvingunum og hótunum og að þvinganir og hótanir séu ekki vænlegar leiðir í kennslu. Hins vegar eru rök gegn endurteknum prófum að það eykur vinnu kennarans að útbúa, finna tíma fyrir, setja fyrir og fara yfir fleiri próf. 

Ef endurskoðun og endurvinnsla eru byggð inn í kannanir og próf, og þau gilda lítið hvert og eitt, er líklega óþarfi að hafa of miklar áhyggjur af endurtekningum á prófum sem ganga ekki vel. Picciotto og Pemantle stinga upp á að nemendur geti unnið úr prófi heima og að sú endurvinnsla geti hækkað einkunn á einhvern hátt (þó ekki upp í hæstu hæðir!)

Það sem sagt er hér að ofan á að mestu við verkefni á formi skriflegra kannana og prófa en það eru auðvitað margar aðrar leiðir sem geta fléttast saman við slík verkefni. Til dæmis eru munnleg próf og kynningar, heimapróf, skýrslur, skapandi skrif og fleira. 

