# Sköpun og skapandi hugsun í stærðfræðimenntun {#skopun}

Nemendur geta verið skapandi í stærðfræði. Hér er fyrst og fremst átt við að nemendur séu stærðfræðilega skapandi en ekki að þeir búi til dæmis til söngtexta eða myndlist utan um fyrir fram gefna stærðfræði. Eftirfarandi umfjöllun byggir á grein Coles og Scott (2015), [Planning for the unexpected in the mathematics classroom: An account of teacher and student change. Research in Mathematics Education, 17(2), 128–147.](https://doi.org/10.1080/14794802.2015.1047787) og 

Það sem getur falist í stærðfræðilegri sköpun eru til dæmis að: 

* nemendur taki eftir einhverju, eða setji eitthvað fram, sem er óvænt og ferskt í umræðu eða við verkefnalausn
* nemendur búi til sín eigin dæmi um stærðfræðilega hluti og sínar eigin stærðfræðilegu skilgreiningar 
* nemendur spyrji eigin spurninga og búi til eigin verkefni
* nemendur fylgi eftir sínum eigin rannsóknum
* nemendur velji sínar eigin leiðir til framsetninga á stærðfræði
* nemendur setji fram sínar eigin tilgátur
* nemendur noti stærðfræði til þess að búa til áhugaverða gripi, áþreifanlega eða með tölvuforritun

Sköpun hér þýðir ekki að um sé að ræða eitthvað alveg nýtt í heiminum heldur eitthvað *nýtt fyrir nemendum*. Nemendur geta verið skapandi hvenær sem er og kennari sem vill stuðla að sköpun nemenda sinna í stærðfærði ætti að reyna að taka eftir því, fagna því og byggja ofan á það þegar það gerist.  

## Dæmi um verkefni þar sem nemendur búa til sína eigin stærðfræðilegu hluti


