# Forsendur stærðfræðimenntunar {#forsendur-staemenntunar}

Af hverju er stærðfræði kennd í skólum? Hvernig á að kenna stærðfræði? Hvað er stærðfræði? Þetta eru allt grundvallarspurningar sem er bæði ómögulegt að svara almennt en það er eiginlega líka ómögulegt fyrir kennara að hafa ekki einhvers konar svör við. Við getum sagt að svörin séu hluti af starfskenningu kennarans og svörin eru ekki altæk heldur hefur hver og einn kennari (vonandi) rökstuddar tilgátur og sýn á þær. 
## Af hverju er stærðfræði kennd í skólum? {#af-hverju-stae}

Um allan heim er stærðfræði skólafag. Stjórnvöld, hvort sem þau eru kosin eða ríkja í krafti einræðis, setja í lög að nemendur skuli læra stærðfræði. Í opinberum námskrám kemur fram hvaða efni sé til náms eða hvaða hæfni skuli stefnt að, og oft fylgja með einhver rök og réttlætingar. Skólafólk, skólastjórar, kennarar og menntafrömuðir setja líka stundum fram ástæður fyrir því að stærðfræði sé kennd í skólum. Sama á við um almenning. 

### Hvað finnst þér? {#thinar-astaedur}

Hvaða ástæður eru til að kenna stærðfræði í skólum? Hvaða ástæður eru réttmætar og hverjar ekki? Skrifið hjá ykkur helstu ástæður sem koma upp í hugann. Þegar þú hefur lokið við það geturðu skoðað nokkrar ástæður í punktunum hér að neðan. Þá er rétt að ígrunda og ræða við aðra og mynda sér dýpri sýn. 

<details class="hint">

<summary>Punktar</summary>

a. Stærðfræði er nauðsynleg fyrir samkeppnishæfni þjóðarinnar.
a. Stærðfræði er nytsamleg fyrir land, þjóð og heiminn. 
a. Stærðfræði er gott tæki til að finna efnilegt bóknámsfólk.
a. Stærðfræði er gagnleg fyrir einstaklinga í daglegu lífi.
a. Stærðfræði ævintýri sem allar manneskjur eiga rétt á að upplifa.
a. Stærðfræði þjálfar hugann.
a. Stærðfræði geymir dýpstu og öruggustu sannindi heimsins. 
a. Stærðfræði er nauðsynleg fyrir hvern og einn til að fá góða atvinnu.

</details>

## Hvernig á að kenna stærðfræði? {#hvernig-stae}

Hugsið ykkur aðstæður þar sem verið er að kenna stærðfræði (þú ímyndar þér að þú sért kennarinn, nemandinn eða áhorfani). Hvað gerir kennarinn og hvað gerir nemandinn? Hvað væri rétt að gera? Hvað væri rangt að gera? 

Ef þú hefur gefið þér stutta stund í þessa ímyndun þá hefurðu gefið þér tilekna gerð af nemanda og aðstæðum og undir niðri er eitthvert tiltekið markmið. Spurningin „hvernig á að kenna stærðfræði“ eða „hvernig er best að kenna stærðfræði“ er auðvitað allt of almenn. Við þurfum að minnsta kosti að taka fram: 

* Hverjum erum við að kenna?
    * Börnum, unglingum, fullorðnum
    * Verðandi kennurum, starfandi læknum

* Í hvaða aðstæðum?
    * Í skólum, kennslustofum, á netinu
    * Blönduðum bekk eða getuskiptum bekk
    * Einum árgangi í einu eða fleirum
    * Alla daga vikunnar eða eitt kvöld í viku

* Með hvaða markmið?
    * Að hinir „bestu“ nái sem lengst og geti tekið við stærðfræðilegu störfunum (séð um að þróa nýja tækni, reiknað út og ákveðið flókin ferli og skipulag, ...)
    * Að allir nái lágmarksfærni í reikningi 
    * Að öll fái að njóta þess að skilja, rökræða og rannsaka stærðfræði

Hver lítur þú á að séu réttmæt markmið með stærðfræðikennslu? Við getum til dæmis hugsað okkur markmið skyldunáms í grunnskóla, en þú gætir líka hugleitt annan vettvang ef hann á betur við. Til dæmis: hver eru markmið stærðfræðikennslu á tiltekinni braut í framhaldsskóla?

## Hvað er stærðfræði? {#hvad-stae}

Til er heil grein heimspekinnar sem reynir að svara spurningunni hvað stærðfræði sé eiginlega. Um það eru gefnar út margar bækur á hverju ári. Fræðasviðið stærðfræðimenntun lítur yfirleitt á málið út frá félagseg og efnislegu sjónarhorni: stærðfræði er allt sem fólk gerir undir heitinu *stærðfræði*. 

### Hvað er stærðfræði í þínum huga? {#stae-thinum-huga}

Hvað er stærðfræði í þínum huga? Hvert er hlutverk stærðfræði fyrir þig, aðra einstaklinga og samfélagið? Skráðu hjá þér þínar hugmyndir áður en þú skoðar punktana. 

<details class="hint">

<summary>Punktar</summary>

a. Reikningur 
a. Að setja upp stærðfræðilíkan af raunverulegum aðstæðum til þess að skilja, stjórna og spá fyrir um framvindu
a. Að rannsaka eðli hugmynda okkar um rými, stærðir, tíma, orsakir, lögmál, regluleika
a. Samfélag stærðfræðinga, stærðfræðinotenda, óslitinn samræðuþráður í meira en tvö þúsund ár

</details>

Allt það sem nefnt er hér í athugasemd fellur undir hatt stærðfræðinnar. Og kannski fannst þú eða aðrir samræðufélagar aðrar hliðar hennar. Fyrir marga er stærðfræði fyrst og fremst reikningur.  

## Niðurstöður stærðfræðimenntunar {#staemennt-statements}

Stærðfræðimenntun hefur verið til sem sjálfstætt fræðasvið í um það bil 50 ár. Rannsóknir í stærðfræðimenntun hafa leitt ýmislegt í ljós en þær geta ekki svarað því hvernig best er að kenna stærðfræði, vegna þess að það fer eftir markmiðunum (og ótalmörgu öðru, sem stærðfræðimenntun hefur einmitt leitt í ljós). Við getum vissulega sagt ýmislegt um hvað er ekki líklegt til árangurs (jafnvel sumt sem virðist vera góð hugmynd) og við getum útskýrt hvers vegna margar spurningar stærðfræðikennslu og -nám eru miklu flóknari en maður gæti haldið við fyrstu sýn. Vel þekkt og gömul tilvitnun segir líka 

> Stærðfræðimenntun er miklu flóknari heldur en þú bjóst við jafnvel þó að þú hafir búist við því að hún væri flóknari en þú bjóst við. (Ed Begle)
